site_name: OpenStreamPoll Documentation
theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.integrate
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky


  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - tables
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yoanbernabeu/OpenStreamPoll
