name: Quality Assurance

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create Database Directory
        run: |
          mkdir -p var
          touch var/test.db
          chmod -R 777 var

      - name: Copy .env.test
        run: cp .env.test .env.test.local

      - name: PHP CS Fixer
        uses: docker://jakzal/phpqa:php8.3
        with:
          args: php-cs-fixer fix ./src --rules=@Symfony --verbose --dry-run

      - name: PHPStan
        uses: docker://jakzal/phpqa:php8.3
        with:
          args: phpstan analyse ./src --level=8

      - name: Security Check
        uses: docker://jakzal/phpqa:php8.3
        with:
          args: local-php-security-checker

      - name: Lint Twig
        uses: docker://jakzal/phpqa:php8.3
        with:
          args: bin/console lint:twig ./templates

      - name: Lint YAML
        uses: docker://jakzal/phpqa:php8.3
        with:
          args: bin/console lint:yaml ./config

      - name: Lint Container
        uses: docker://jakzal/phpqa:php8.3
        with:
          args: bin/console lint:container

      - name: Create Database Schema
        uses: docker://jakzal/phpqa:php8.3
        env:
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/test.db"
          APP_ENV: test
        with:
          args: bin/console doctrine:schema:create --env=test

      - name: Run Migrations
        uses: docker://jakzal/phpqa:php8.3
        env:
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/test.db"
          APP_ENV: test
        with:
          args: bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Load Fixtures
        uses: docker://jakzal/phpqa:php8.3
        env:
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/test.db"
          APP_ENV: test
        with:
          args: bin/console doctrine:fixtures:load --no-interaction --env=test

      - name: Run Tests
        uses: docker://jakzal/phpqa:php8.3
        env:
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/test.db"
          APP_ENV: test
        with:
          args: bin/phpunit --testdox